CREATE TABLE ban_clb (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tenBan VARCHAR(255) NOT NULL UNIQUE,
  moTa TEXT,
  loai ENUM('Ban', 'TieuBan') NOT NULL,
  banChaId INT DEFAULT NULL,
  ngayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ban_cha FOREIGN KEY (banChaId) REFERENCES ban_clb(id)
);
