CREATE TABLE THU_QUY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    Ban NVARCHAR(100) NOT NULL,
    SoTien INT NOT NULL,
    LyDo NVARCHAR(255),
    ThoiGianNop DATETIME NOT NULL,
    GhiChu NVARCHAR(255)
);

INSERT INTO THU_QUY (HoTen, Ban, SoTien, LyDo, ThoiGianNop)
VALUES ('Nguyen Van A', 'Ban Truyen Thong', 50000, 'Thu quy thang 9', NOW());

SELECT * FROM THU_QUY;
SELECT SUM(SoTien) AS TongTienThu FROM THU_QUY;
